[project]
author = "squid-kid"
entry = "simpleStorage.sw"
license = "Apache-2.0"
name = "oru_project"

[dependencies]
core = { git = "http://github.com/FuelLabs/sway-lib-core" }
std = { git = "http://github.com/FuelLabs/sway-lib-std" }
